FROM gradle:8.4.0-jdk17 AS build

WORKDIR /home/cabeceira

COPY build.gradle .
COPY settings.gradle .
COPY src /home/cabeceira/src

RUN gradle clean build -x test

FROM openjdk:17

WORKDIR /home/cabeceira

COPY --from=build /home/user/.gradle/caches/modules-2/files-2.1/com.mysql/mysql-connector-j/8.0.33/.../mysql-connector-java-8.0.33.jar .

COPY --from=build /home/cabeceira/build/libs/api-0.0.1-SNAPSHOT.jar .

ENTRYPOINT ["java", "-jar", "api-0.0.1-SNAPSHOT.jar"]
